# Generated by Django 4.2.7 on 2025-05-23 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False, verbose_name='Numero VLAN')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome VLAN')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione')),
                ('subnet', models.CharField(blank=True, max_length=18, null=True, verbose_name='Subnet')),
                ('gateway', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='Gateway')),
            ],
            options={
                'verbose_name': 'VLAN',
                'verbose_name_plural': 'VLAN',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='IndirizzoIP',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, protocol='IPv4', serialize=False, verbose_name='Indirizzo IP')),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True, verbose_name='MAC Address')),
                ('stato', models.CharField(choices=[('attivo', 'Attivo'), ('disattivo', 'Disattivo'), ('riservato', 'Riservato')], default='disattivo', max_length=20, verbose_name='Stato')),
                ('responsabile', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Mail Responsabile')),
                ('utente_finale', models.CharField(blank=True, max_length=255, null=True, verbose_name='Utente Finale')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('ultimo_controllo', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ultimo Controllo')),
                ('data_creazione', models.DateTimeField(auto_now_add=True, verbose_name='Data Creazione')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Data Modifica')),
                ('data_scadenza', models.DateTimeField(blank=True, null=True, verbose_name='Data Scadenza')),
                ('assegnato_a_utente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indirizzi_assegnati', to=settings.AUTH_USER_MODEL, verbose_name='Assegnato a')),
            ],
            options={
                'verbose_name': 'Indirizzo IP',
                'verbose_name_plural': 'Indirizzi IP',
                'ordering': ['ip'],
            },
        ),
    ]
