# Generated by Django 4.2.7 on 2025-05-23 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reti_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indirizzoip',
            name='vlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indirizzi', to='reti_app.vlan', verbose_name='VLAN'),
        ),
    ]
