# Generated by Django 4.2.7 on 2025-05-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reti_app', '0002_indirizzoip_vlan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indirizzoip',
            name='data_modifica',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Data Modifica'),
        ),
        migrations.AlterField(
            model_name='indirizzoip',
            name='data_scadenza',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data Scadenza'),
        ),
        migrations.AlterField(
            model_name='indirizzoip',
            name='mac_address',
            field=models.CharField(blank=True, db_index=True, max_length=17, null=True, verbose_name='MAC Address'),
        ),
        migrations.AlterField(
            model_name='indirizzoip',
            name='responsabile',
            field=models.EmailField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Mail Responsabile'),
        ),
        migrations.AlterField(
            model_name='indirizzoip',
            name='stato',
            field=models.CharField(choices=[('attivo', 'Attivo'), ('disattivo', 'Disattivo'), ('riservato', 'Riservato')], db_index=True, default='disattivo', max_length=20, verbose_name='Stato'),
        ),
        migrations.AddIndex(
            model_name='indirizzoip',
            index=models.Index(fields=['stato', 'vlan'], name='reti_app_in_stato_81506b_idx'),
        ),
        migrations.AddIndex(
            model_name='indirizzoip',
            index=models.Index(fields=['stato', 'assegnato_a_utente'], name='reti_app_in_stato_c5502b_idx'),
        ),
        migrations.AddIndex(
            model_name='indirizzoip',
            index=models.Index(fields=['data_scadenza', 'stato'], name='reti_app_in_data_sc_ea190f_idx'),
        ),
    ]
