# Generated by Django 4.2.7 on 2025-05-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reti_app', '0003_alter_indirizzoip_data_modifica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vlan',
            name='subnet',
        ),
        migrations.AddField(
            model_name='vlan',
            name='subnets',
            field=models.TextField(blank=True, help_text='Lista di subnet separate da virgola o nuova linea', null=True, verbose_name='Subnets'),
        ),
    ]
