# Generated by Django 4.2.7 on 2025-05-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reti_app', '0004_remove_vlan_subnet_vlan_subnets'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlan',
            name='num_indirizzi',
            field=models.IntegerField(default=0, help_text='Campo aggiornato periodicamente tramite cron job', verbose_name='Numero di indirizzi IP'),
        ),
    ]
