# Generated by Django 4.2.7 on 2025-05-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reti_app', '0005_vlan_num_indirizzi'),
    ]

    operations = [
        migrations.AddField(
            model_name='indirizzoip',
            name='disponibilita',
            field=models.CharField(choices=[('libero', 'Libero'), ('usato', 'Usato')], db_index=True, default='libero', help_text="Indica se l'IP è stato richiesto da qualche utente", max_length=20, verbose_name='Disponibilità'),
        ),
        migrations.AlterField(
            model_name='indirizzoip',
            name='stato',
            field=models.CharField(choices=[('attivo', 'Attivo'), ('disattivo', 'Disattivo'), ('riservato', 'Riservato')], db_index=True, default='disattivo', help_text="Indica se l'IP sta navigando in rete", max_length=20, verbose_name='Stato Rete'),
        ),
        migrations.AddIndex(
            model_name='indirizzoip',
            index=models.Index(fields=['disponibilita', 'stato'], name='reti_app_in_disponi_9634a5_idx'),
        ),
    ]
