# Generated by Django 4.2.7 on 2025-05-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reti_app', '0006_add_disponibilita_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indirizzoip',
            name='stato',
            field=models.CharField(choices=[('attivo', 'Attivo'), ('disattivo', 'Disattivo')], db_index=True, default='disattivo', help_text="Indica se l'IP sta navigando in rete", max_length=20, verbose_name='Stato Rete'),
        ),
    ]
