# Generated by Django 4.2.7 on 2025-05-30 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reti_app', '0008_configurazionescadenze'),
    ]

    operations = [
    ]
