# Generated by Django 4.2.7 on 2025-05-30 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reti_app', '0009_auto_20250530_1731'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfigurazioneScadenze',
        ),
    ]
