# Generated by Django 4.2.7 on 2025-06-06 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reti_app', '0010_delete_configurazionescadenze'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoricoResponsabile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsabile', models.EmailField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Mail Responsabile')),
                ('utente_finale', models.CharField(blank=True, max_length=255, null=True, verbose_name='Utente Finale')),
                ('data_inizio', models.DateTimeField(db_index=True, verbose_name='Data Inizio Assegnazione')),
                ('data_fine', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data Fine Assegnazione')),
                ('motivo_cambio', models.CharField(blank=True, choices=[('assegnazione', 'Assegnazione Iniziale'), ('rilascio', 'Rilascio Volontario'), ('inattivita', 'Liberazione per Inattività'), ('scadenza', 'Liberazione per Scadenza'), ('cambio', 'Cambio Responsabile'), ('pulizia_automatica', 'Pulizia Automatica'), ('admin', 'Modifica Amministratore')], max_length=30, null=True, verbose_name='Motivo Cambio')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('stato_rete', models.CharField(blank=True, max_length=20, null=True, verbose_name='Stato Rete al momento')),
                ('disponibilita', models.CharField(blank=True, max_length=20, null=True, verbose_name='Disponibilità al momento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('created_by', models.CharField(blank=True, help_text='Sistema o utente che ha creato il record', max_length=100, null=True, verbose_name='Creato da')),
                ('indirizzo_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storico_responsabili', to='reti_app.indirizzoip', verbose_name='Indirizzo IP')),
                ('vlan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reti_app.vlan', verbose_name='VLAN al momento')),
            ],
            options={
                'verbose_name': 'Storico Responsabile',
                'verbose_name_plural': 'Storico Responsabili',
                'ordering': ['-data_inizio'],
                'indexes': [models.Index(fields=['indirizzo_ip', '-data_inizio'], name='reti_app_st_indiriz_fc7e07_idx'), models.Index(fields=['responsabile', '-data_inizio'], name='reti_app_st_respons_419c5c_idx'), models.Index(fields=['data_inizio', 'data_fine'], name='reti_app_st_data_in_6bb5fb_idx')],
            },
        ),
    ]
