# Generated by Django 4.2.7 on 2025-06-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reti_app', '0012_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='login_enabled',
            field=models.BooleanField(default=False, help_text="Se disabilitato, l'utente non potrà fare login anche se autenticato tramite LDAP", verbose_name='Login Abilitato'),
        ),
    ]
