# Generated by Django 4.2.7 on 2025-06-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reti_app', '0013_update_login_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indirizzoip',
            name='disponibilita',
            field=models.CharField(choices=[('libero', 'Libero'), ('usato', 'Usato'), ('riservato', 'Riservato')], db_index=True, default='libero', help_text='Libero: disponibile per richieste | Usato: assegnato a un utente | Riservato: non assegnabile temporaneamente', max_length=20, verbose_name='Disponibilità'),
        ),
    ]
